Repository robotology/icub-firmware, pull requests merged in 2024-03, with the labels that each got.

#478 amcbldc v2.0.11 + amc2c v3.0.1.0 Handling of overcurrent flag w/ the new codegen
  emBODY/eBcode/arch-arm/board/amc2c/application/src/app-board-amc2c/embot_app_board_amc2c_info.cpp
  emBODY/eBcode/arch-arm/board/amcbldc/application/src/app-board-amcbldc/embot_app_board_amcbldc_info.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/amc-bldc/AMC_BLDC.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/amc-bldc/AMC_BLDC.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/amc-bldc/AMC_BLDC_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/amc-bldc/AMC_BLDC_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-decoder/can_decoder.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-decoder/can_decoder.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-decoder/can_decoder_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-decoder/can_decoder_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-encoder/can_encoder.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-encoder/can_encoder.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-encoder/can_encoder_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/can-encoder/can_encoder_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/FOCInnerLoop.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/FOCInnerLoop.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/control_foc.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/control_foc.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/control_foc_data.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/control_foc_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-foc/control_foc_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-outer/control_outer.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-outer/control_outer.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-outer/control_outer_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/control-outer/control_outer_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/estimator/estimation_velocity.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/estimator/estimation_velocity.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/estimator/estimation_velocity_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/estimator/estimation_velocity_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/filter-current/filter_current.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/filter-current/filter_current.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/filter-current/filter_current_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/filter-current/filter_current_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-rx/SupervisorFSM_RX.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-rx/SupervisorFSM_RX.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-rx/SupervisorFSM_RX_data.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-rx/SupervisorFSM_RX_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-rx/SupervisorFSM_RX_types.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-tx/SupervisorFSM_TX.cpp
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-tx/SupervisorFSM_TX.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-tx/SupervisorFSM_TX_private.h
  emBODY/eBcode/arch-arm/mbd/amcbldc/supervisor-tx/SupervisorFSM_TX_types.h
Labels: enhancement

#480 Feat/amc2c vcc reading
  emBODY/eBcode/arch-arm/board/amc2c/application/src/app-board-amc2c/embot_app_board_amc2c_theMBD.cpp
  emBODY/eBcode/arch-arm/board/amc2c/bsp/embot_hw_bsp_amc2c.cpp
  emBODY/eBcode/arch-arm/board/amc2c/bsp/embot_hw_bsp_amc2c.h
  emBODY/eBcode/arch-arm/board/amc2c/bsp/embot_hw_motor_bsp_amc2c.cpp
  emBODY/eBcode/arch-arm/board/amc2c/bsp/embot_hw_motor_bsp_amc2c.h
  emBODY/eBcode/arch-arm/board/amc2c/bsp/motorhal/adcm.c
  emBODY/eBcode/arch-arm/board/amc2c/bsp/motorhal/motorhal.cpp
  emBODY/eBcode/arch-arm/board/amc2c/bsp/motorhal/motorhal.h
  emBODY/eBcode/arch-arm/board/amcbldc/application/src/app-board-amcbldc/embot_app_board_amcbldc_theMBD.cpp
  emBODY/eBcode/arch-arm/embot/app/bldc/embot_app_bldc.h
  emBODY/eBcode/arch-arm/embot/hw/embot_hw_motor.cpp
  emBODY/eBcode/arch-arm/embot/hw/embot_hw_motor.h
  emBODY/eBcode/arch-arm/libs/lowlevel/stm32hal/src/board/amc/v1A0/inc/res_mgr_conf.h
  emBODY/eBcode/arch-arm/libs/lowlevel/stm32hal/src/board/amc2c/v1A0/inc/main.h
Labels: enhancement, bugfix

#484 Fix/versions alignment amc2c v3.0.3 + amcbldc 2.0.13
  emBODY/eBcode/arch-arm/board/amc2c/application/src/app-board-amc2c/embot_app_board_amc2c_info.cpp
  emBODY/eBcode/arch-arm/board/amc2c/bsp/motorhal/motorhal.h
  emBODY/eBcode/arch-arm/board/amcbldc/application/src/app-board-amcbldc/embot_app_board_amcbldc_info.cpp
Labels: bugfix

#485 AMC - fix programmed packets count
  emBODY/eBcode/arch-arm/board/amc/environment/eupdater/src/eupdater/updater-core.c
Labels: bugfix
